export const LOADING = "LOADING";
export const DATA_FETCHED = "DATA_FETCHED";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART= "DELETE_FROM_CART";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART = "UPDATE_CART";